# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MmLKEsiFS4xOqLOjvAuGY123QkWpaAcz
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("https://github.com/stulasiprasad/CSE4036-Lab-2/raw/main/iris_dataset.csv")
df

#Data Preprocessing 
x=df.iloc[:,:-1].values
y=df.iloc[:,:].values

#Division of Data
#Training data 80% and Test data 20%
from sklearn.model_selection import train_test_split as tts

xtrain,xtest,ytrain,ytest=tts(x,y,test_size=0.20)

#Data Scaling 
from sklearn.preprocessing import StandardScaler 
ss=StandardScaler()
ss.fit(xtrain)
xtrain=ss.transform(xtrain)
xtest=ss.transform(xtest)

print(type(xtrain))
print(type(ytrain))

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5)
classifier.fit(xtrain.astype(str), ytrain.astype(str))

ypred=classifier.predict(xtest)

print(ypred.astype(str))

#Results

from sklearn.metrics import classification_report , confusion_matrix , accuracy_score 
#result=confusion_matrix(ytest.astype(str),ypred)

result=classification_report(ytest,ypred)